//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace etWeb.et {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FachadaSoap", Namespace="http://tempuri.org/")]
    public partial class Fachada : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerPermisosPorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaPorRolOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaClientePorAgenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback borrarUsuarioPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback usuarioPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaEncuestasOperationCompleted;
        
        private System.Threading.SendOrPostCallback encuestaPorIdPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback encuestaPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPreguntaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaEncuestasPorIdAgenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaEncuestasPorIdClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarEncuestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarEncuestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaEncuestasPorFechaIngresoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaEncuestasPorFechaVigenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaEncuestasPorFechaCierreOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback rolPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarRolOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarRolOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Fachada() {
            this.Url = global::etWeb.Properties.Settings.Default.etWeb_localhost_Fachada;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validarUsuarioCompletedEventHandler validarUsuarioCompleted;
        
        /// <remarks/>
        public event obtenerPermisosPorUsuarioCompletedEventHandler obtenerPermisosPorUsuarioCompleted;
        
        /// <remarks/>
        public event listaUsuariosCompletedEventHandler listaUsuariosCompleted;
        
        /// <remarks/>
        public event listaPorRolCompletedEventHandler listaPorRolCompleted;
        
        /// <remarks/>
        public event listaClientePorAgenteCompletedEventHandler listaClientePorAgenteCompleted;
        
        /// <remarks/>
        public event borrarUsuarioPorIdCompletedEventHandler borrarUsuarioPorIdCompleted;
        
        /// <remarks/>
        public event usuarioPorIdCompletedEventHandler usuarioPorIdCompleted;
        
        /// <remarks/>
        public event insertarUsuarioCompletedEventHandler insertarUsuarioCompleted;
        
        /// <remarks/>
        public event actualizarUsuarioCompletedEventHandler actualizarUsuarioCompleted;
        
        /// <remarks/>
        public event listaEncuestasCompletedEventHandler listaEncuestasCompleted;
        
        /// <remarks/>
        public event encuestaPorIdPasswordCompletedEventHandler encuestaPorIdPasswordCompleted;
        
        /// <remarks/>
        public event encuestaPorIdCompletedEventHandler encuestaPorIdCompleted;
        
        /// <remarks/>
        public event getPreguntaCompletedEventHandler getPreguntaCompleted;
        
        /// <remarks/>
        public event listaEncuestasPorIdAgenteCompletedEventHandler listaEncuestasPorIdAgenteCompleted;
        
        /// <remarks/>
        public event listaEncuestasPorIdClienteCompletedEventHandler listaEncuestasPorIdClienteCompleted;
        
        /// <remarks/>
        public event insertarEncuestaCompletedEventHandler insertarEncuestaCompleted;
        
        /// <remarks/>
        public event actualizarEncuestaCompletedEventHandler actualizarEncuestaCompleted;
        
        /// <remarks/>
        public event listaEncuestasPorFechaIngresoCompletedEventHandler listaEncuestasPorFechaIngresoCompleted;
        
        /// <remarks/>
        public event listaEncuestasPorFechaVigenciaCompletedEventHandler listaEncuestasPorFechaVigenciaCompleted;
        
        /// <remarks/>
        public event listaEncuestasPorFechaCierreCompletedEventHandler listaEncuestasPorFechaCierreCompleted;
        
        /// <remarks/>
        public event listaRolesCompletedEventHandler listaRolesCompleted;
        
        /// <remarks/>
        public event rolPorIdCompletedEventHandler rolPorIdCompleted;
        
        /// <remarks/>
        public event insertarRolCompletedEventHandler insertarRolCompleted;
        
        /// <remarks/>
        public event actualizarRolCompletedEventHandler actualizarRolCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validarUsuario(string usuario, string password) {
            object[] results = this.Invoke("validarUsuario", new object[] {
                        usuario,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validarUsuarioAsync(string usuario, string password) {
            this.validarUsuarioAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void validarUsuarioAsync(string usuario, string password, object userState) {
            if ((this.validarUsuarioOperationCompleted == null)) {
                this.validarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarUsuarioOperationCompleted);
            }
            this.InvokeAsync("validarUsuario", new object[] {
                        usuario,
                        password}, this.validarUsuarioOperationCompleted, userState);
        }
        
        private void OnvalidarUsuarioOperationCompleted(object arg) {
            if ((this.validarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarUsuarioCompleted(this, new validarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerPermisosPorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerPermisosPorUsuario(string usuario) {
            object[] results = this.Invoke("obtenerPermisosPorUsuario", new object[] {
                        usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPermisosPorUsuarioAsync(string usuario) {
            this.obtenerPermisosPorUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void obtenerPermisosPorUsuarioAsync(string usuario, object userState) {
            if ((this.obtenerPermisosPorUsuarioOperationCompleted == null)) {
                this.obtenerPermisosPorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPermisosPorUsuarioOperationCompleted);
            }
            this.InvokeAsync("obtenerPermisosPorUsuario", new object[] {
                        usuario}, this.obtenerPermisosPorUsuarioOperationCompleted, userState);
        }
        
        private void OnobtenerPermisosPorUsuarioOperationCompleted(object arg) {
            if ((this.obtenerPermisosPorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPermisosPorUsuarioCompleted(this, new obtenerPermisosPorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usuario[] listaUsuarios() {
            object[] results = this.Invoke("listaUsuarios", new object[0]);
            return ((usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void listaUsuariosAsync() {
            this.listaUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void listaUsuariosAsync(object userState) {
            if ((this.listaUsuariosOperationCompleted == null)) {
                this.listaUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaUsuariosOperationCompleted);
            }
            this.InvokeAsync("listaUsuarios", new object[0], this.listaUsuariosOperationCompleted, userState);
        }
        
        private void OnlistaUsuariosOperationCompleted(object arg) {
            if ((this.listaUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaUsuariosCompleted(this, new listaUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaPorRol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usuario[] listaPorRol(string rol) {
            object[] results = this.Invoke("listaPorRol", new object[] {
                        rol});
            return ((usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void listaPorRolAsync(string rol) {
            this.listaPorRolAsync(rol, null);
        }
        
        /// <remarks/>
        public void listaPorRolAsync(string rol, object userState) {
            if ((this.listaPorRolOperationCompleted == null)) {
                this.listaPorRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaPorRolOperationCompleted);
            }
            this.InvokeAsync("listaPorRol", new object[] {
                        rol}, this.listaPorRolOperationCompleted, userState);
        }
        
        private void OnlistaPorRolOperationCompleted(object arg) {
            if ((this.listaPorRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaPorRolCompleted(this, new listaPorRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaClientePorAgente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usuario[] listaClientePorAgente(string nombreAgente) {
            object[] results = this.Invoke("listaClientePorAgente", new object[] {
                        nombreAgente});
            return ((usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void listaClientePorAgenteAsync(string nombreAgente) {
            this.listaClientePorAgenteAsync(nombreAgente, null);
        }
        
        /// <remarks/>
        public void listaClientePorAgenteAsync(string nombreAgente, object userState) {
            if ((this.listaClientePorAgenteOperationCompleted == null)) {
                this.listaClientePorAgenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaClientePorAgenteOperationCompleted);
            }
            this.InvokeAsync("listaClientePorAgente", new object[] {
                        nombreAgente}, this.listaClientePorAgenteOperationCompleted, userState);
        }
        
        private void OnlistaClientePorAgenteOperationCompleted(object arg) {
            if ((this.listaClientePorAgenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaClientePorAgenteCompleted(this, new listaClientePorAgenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/borrarUsuarioPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool borrarUsuarioPorId(string id) {
            object[] results = this.Invoke("borrarUsuarioPorId", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void borrarUsuarioPorIdAsync(string id) {
            this.borrarUsuarioPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void borrarUsuarioPorIdAsync(string id, object userState) {
            if ((this.borrarUsuarioPorIdOperationCompleted == null)) {
                this.borrarUsuarioPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnborrarUsuarioPorIdOperationCompleted);
            }
            this.InvokeAsync("borrarUsuarioPorId", new object[] {
                        id}, this.borrarUsuarioPorIdOperationCompleted, userState);
        }
        
        private void OnborrarUsuarioPorIdOperationCompleted(object arg) {
            if ((this.borrarUsuarioPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.borrarUsuarioPorIdCompleted(this, new borrarUsuarioPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/usuarioPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usuario usuarioPorId(string id) {
            object[] results = this.Invoke("usuarioPorId", new object[] {
                        id});
            return ((usuario)(results[0]));
        }
        
        /// <remarks/>
        public void usuarioPorIdAsync(string id) {
            this.usuarioPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void usuarioPorIdAsync(string id, object userState) {
            if ((this.usuarioPorIdOperationCompleted == null)) {
                this.usuarioPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnusuarioPorIdOperationCompleted);
            }
            this.InvokeAsync("usuarioPorId", new object[] {
                        id}, this.usuarioPorIdOperationCompleted, userState);
        }
        
        private void OnusuarioPorIdOperationCompleted(object arg) {
            if ((this.usuarioPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.usuarioPorIdCompleted(this, new usuarioPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertarUsuario(usuario unUsuario) {
            object[] results = this.Invoke("insertarUsuario", new object[] {
                        unUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertarUsuarioAsync(usuario unUsuario) {
            this.insertarUsuarioAsync(unUsuario, null);
        }
        
        /// <remarks/>
        public void insertarUsuarioAsync(usuario unUsuario, object userState) {
            if ((this.insertarUsuarioOperationCompleted == null)) {
                this.insertarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarUsuarioOperationCompleted);
            }
            this.InvokeAsync("insertarUsuario", new object[] {
                        unUsuario}, this.insertarUsuarioOperationCompleted, userState);
        }
        
        private void OninsertarUsuarioOperationCompleted(object arg) {
            if ((this.insertarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarUsuarioCompleted(this, new insertarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarUsuario(string id, usuario unUsuario) {
            object[] results = this.Invoke("actualizarUsuario", new object[] {
                        id,
                        unUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarUsuarioAsync(string id, usuario unUsuario) {
            this.actualizarUsuarioAsync(id, unUsuario, null);
        }
        
        /// <remarks/>
        public void actualizarUsuarioAsync(string id, usuario unUsuario, object userState) {
            if ((this.actualizarUsuarioOperationCompleted == null)) {
                this.actualizarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarUsuarioOperationCompleted);
            }
            this.InvokeAsync("actualizarUsuario", new object[] {
                        id,
                        unUsuario}, this.actualizarUsuarioOperationCompleted, userState);
        }
        
        private void OnactualizarUsuarioOperationCompleted(object arg) {
            if ((this.actualizarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarUsuarioCompleted(this, new actualizarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaEncuestas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaEncuestaResult listaEncuestas() {
            object[] results = this.Invoke("listaEncuestas", new object[0]);
            return ((ListaEncuestaResult)(results[0]));
        }
        
        /// <remarks/>
        public void listaEncuestasAsync() {
            this.listaEncuestasAsync(null);
        }
        
        /// <remarks/>
        public void listaEncuestasAsync(object userState) {
            if ((this.listaEncuestasOperationCompleted == null)) {
                this.listaEncuestasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaEncuestasOperationCompleted);
            }
            this.InvokeAsync("listaEncuestas", new object[0], this.listaEncuestasOperationCompleted, userState);
        }
        
        private void OnlistaEncuestasOperationCompleted(object arg) {
            if ((this.listaEncuestasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaEncuestasCompleted(this, new listaEncuestasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/encuestaPorIdPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultWs encuestaPorIdPassword(int id, string pass) {
            object[] results = this.Invoke("encuestaPorIdPassword", new object[] {
                        id,
                        pass});
            return ((ResultWs)(results[0]));
        }
        
        /// <remarks/>
        public void encuestaPorIdPasswordAsync(int id, string pass) {
            this.encuestaPorIdPasswordAsync(id, pass, null);
        }
        
        /// <remarks/>
        public void encuestaPorIdPasswordAsync(int id, string pass, object userState) {
            if ((this.encuestaPorIdPasswordOperationCompleted == null)) {
                this.encuestaPorIdPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnencuestaPorIdPasswordOperationCompleted);
            }
            this.InvokeAsync("encuestaPorIdPassword", new object[] {
                        id,
                        pass}, this.encuestaPorIdPasswordOperationCompleted, userState);
        }
        
        private void OnencuestaPorIdPasswordOperationCompleted(object arg) {
            if ((this.encuestaPorIdPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encuestaPorIdPasswordCompleted(this, new encuestaPorIdPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/encuestaPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaEncuestaResult encuestaPorId(string id) {
            object[] results = this.Invoke("encuestaPorId", new object[] {
                        id});
            return ((ListaEncuestaResult)(results[0]));
        }
        
        /// <remarks/>
        public void encuestaPorIdAsync(string id) {
            this.encuestaPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void encuestaPorIdAsync(string id, object userState) {
            if ((this.encuestaPorIdOperationCompleted == null)) {
                this.encuestaPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnencuestaPorIdOperationCompleted);
            }
            this.InvokeAsync("encuestaPorId", new object[] {
                        id}, this.encuestaPorIdOperationCompleted, userState);
        }
        
        private void OnencuestaPorIdOperationCompleted(object arg) {
            if ((this.encuestaPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encuestaPorIdCompleted(this, new encuestaPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPregunta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultWs getPregunta(int idEncuesta, string pass, respuesta respuesta) {
            object[] results = this.Invoke("getPregunta", new object[] {
                        idEncuesta,
                        pass,
                        respuesta});
            return ((ResultWs)(results[0]));
        }
        
        /// <remarks/>
        public void getPreguntaAsync(int idEncuesta, string pass, respuesta respuesta) {
            this.getPreguntaAsync(idEncuesta, pass, respuesta, null);
        }
        
        /// <remarks/>
        public void getPreguntaAsync(int idEncuesta, string pass, respuesta respuesta, object userState) {
            if ((this.getPreguntaOperationCompleted == null)) {
                this.getPreguntaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPreguntaOperationCompleted);
            }
            this.InvokeAsync("getPregunta", new object[] {
                        idEncuesta,
                        pass,
                        respuesta}, this.getPreguntaOperationCompleted, userState);
        }
        
        private void OngetPreguntaOperationCompleted(object arg) {
            if ((this.getPreguntaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPreguntaCompleted(this, new getPreguntaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaEncuestasPorIdAgente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public encuesta[] listaEncuestasPorIdAgente(string idAgente) {
            object[] results = this.Invoke("listaEncuestasPorIdAgente", new object[] {
                        idAgente});
            return ((encuesta[])(results[0]));
        }
        
        /// <remarks/>
        public void listaEncuestasPorIdAgenteAsync(string idAgente) {
            this.listaEncuestasPorIdAgenteAsync(idAgente, null);
        }
        
        /// <remarks/>
        public void listaEncuestasPorIdAgenteAsync(string idAgente, object userState) {
            if ((this.listaEncuestasPorIdAgenteOperationCompleted == null)) {
                this.listaEncuestasPorIdAgenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaEncuestasPorIdAgenteOperationCompleted);
            }
            this.InvokeAsync("listaEncuestasPorIdAgente", new object[] {
                        idAgente}, this.listaEncuestasPorIdAgenteOperationCompleted, userState);
        }
        
        private void OnlistaEncuestasPorIdAgenteOperationCompleted(object arg) {
            if ((this.listaEncuestasPorIdAgenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaEncuestasPorIdAgenteCompleted(this, new listaEncuestasPorIdAgenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaEncuestasPorIdCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public encuesta[] listaEncuestasPorIdCliente(string idCliente) {
            object[] results = this.Invoke("listaEncuestasPorIdCliente", new object[] {
                        idCliente});
            return ((encuesta[])(results[0]));
        }
        
        /// <remarks/>
        public void listaEncuestasPorIdClienteAsync(string idCliente) {
            this.listaEncuestasPorIdClienteAsync(idCliente, null);
        }
        
        /// <remarks/>
        public void listaEncuestasPorIdClienteAsync(string idCliente, object userState) {
            if ((this.listaEncuestasPorIdClienteOperationCompleted == null)) {
                this.listaEncuestasPorIdClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaEncuestasPorIdClienteOperationCompleted);
            }
            this.InvokeAsync("listaEncuestasPorIdCliente", new object[] {
                        idCliente}, this.listaEncuestasPorIdClienteOperationCompleted, userState);
        }
        
        private void OnlistaEncuestasPorIdClienteOperationCompleted(object arg) {
            if ((this.listaEncuestasPorIdClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaEncuestasPorIdClienteCompleted(this, new listaEncuestasPorIdClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarEncuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertarEncuesta(encuesta unaEncuesta) {
            object[] results = this.Invoke("insertarEncuesta", new object[] {
                        unaEncuesta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertarEncuestaAsync(encuesta unaEncuesta) {
            this.insertarEncuestaAsync(unaEncuesta, null);
        }
        
        /// <remarks/>
        public void insertarEncuestaAsync(encuesta unaEncuesta, object userState) {
            if ((this.insertarEncuestaOperationCompleted == null)) {
                this.insertarEncuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarEncuestaOperationCompleted);
            }
            this.InvokeAsync("insertarEncuesta", new object[] {
                        unaEncuesta}, this.insertarEncuestaOperationCompleted, userState);
        }
        
        private void OninsertarEncuestaOperationCompleted(object arg) {
            if ((this.insertarEncuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarEncuestaCompleted(this, new insertarEncuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarEncuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarEncuesta(string id, encuesta unaEncuesta) {
            object[] results = this.Invoke("actualizarEncuesta", new object[] {
                        id,
                        unaEncuesta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarEncuestaAsync(string id, encuesta unaEncuesta) {
            this.actualizarEncuestaAsync(id, unaEncuesta, null);
        }
        
        /// <remarks/>
        public void actualizarEncuestaAsync(string id, encuesta unaEncuesta, object userState) {
            if ((this.actualizarEncuestaOperationCompleted == null)) {
                this.actualizarEncuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarEncuestaOperationCompleted);
            }
            this.InvokeAsync("actualizarEncuesta", new object[] {
                        id,
                        unaEncuesta}, this.actualizarEncuestaOperationCompleted, userState);
        }
        
        private void OnactualizarEncuestaOperationCompleted(object arg) {
            if ((this.actualizarEncuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarEncuestaCompleted(this, new actualizarEncuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaEncuestasPorFechaIngreso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public encuesta[] listaEncuestasPorFechaIngreso(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente) {
            object[] results = this.Invoke("listaEncuestasPorFechaIngreso", new object[] {
                        fechaInicial,
                        fechaFinal,
                        idAgente});
            return ((encuesta[])(results[0]));
        }
        
        /// <remarks/>
        public void listaEncuestasPorFechaIngresoAsync(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente) {
            this.listaEncuestasPorFechaIngresoAsync(fechaInicial, fechaFinal, idAgente, null);
        }
        
        /// <remarks/>
        public void listaEncuestasPorFechaIngresoAsync(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente, object userState) {
            if ((this.listaEncuestasPorFechaIngresoOperationCompleted == null)) {
                this.listaEncuestasPorFechaIngresoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaEncuestasPorFechaIngresoOperationCompleted);
            }
            this.InvokeAsync("listaEncuestasPorFechaIngreso", new object[] {
                        fechaInicial,
                        fechaFinal,
                        idAgente}, this.listaEncuestasPorFechaIngresoOperationCompleted, userState);
        }
        
        private void OnlistaEncuestasPorFechaIngresoOperationCompleted(object arg) {
            if ((this.listaEncuestasPorFechaIngresoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaEncuestasPorFechaIngresoCompleted(this, new listaEncuestasPorFechaIngresoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaEncuestasPorFechaVigencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public encuesta[] listaEncuestasPorFechaVigencia(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente) {
            object[] results = this.Invoke("listaEncuestasPorFechaVigencia", new object[] {
                        fechaInicial,
                        fechaFinal,
                        idAgente});
            return ((encuesta[])(results[0]));
        }
        
        /// <remarks/>
        public void listaEncuestasPorFechaVigenciaAsync(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente) {
            this.listaEncuestasPorFechaVigenciaAsync(fechaInicial, fechaFinal, idAgente, null);
        }
        
        /// <remarks/>
        public void listaEncuestasPorFechaVigenciaAsync(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente, object userState) {
            if ((this.listaEncuestasPorFechaVigenciaOperationCompleted == null)) {
                this.listaEncuestasPorFechaVigenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaEncuestasPorFechaVigenciaOperationCompleted);
            }
            this.InvokeAsync("listaEncuestasPorFechaVigencia", new object[] {
                        fechaInicial,
                        fechaFinal,
                        idAgente}, this.listaEncuestasPorFechaVigenciaOperationCompleted, userState);
        }
        
        private void OnlistaEncuestasPorFechaVigenciaOperationCompleted(object arg) {
            if ((this.listaEncuestasPorFechaVigenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaEncuestasPorFechaVigenciaCompleted(this, new listaEncuestasPorFechaVigenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaEncuestasPorFechaCierre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public encuesta[] listaEncuestasPorFechaCierre(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente) {
            object[] results = this.Invoke("listaEncuestasPorFechaCierre", new object[] {
                        fechaInicial,
                        fechaFinal,
                        idAgente});
            return ((encuesta[])(results[0]));
        }
        
        /// <remarks/>
        public void listaEncuestasPorFechaCierreAsync(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente) {
            this.listaEncuestasPorFechaCierreAsync(fechaInicial, fechaFinal, idAgente, null);
        }
        
        /// <remarks/>
        public void listaEncuestasPorFechaCierreAsync(System.DateTime fechaInicial, System.DateTime fechaFinal, string idAgente, object userState) {
            if ((this.listaEncuestasPorFechaCierreOperationCompleted == null)) {
                this.listaEncuestasPorFechaCierreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaEncuestasPorFechaCierreOperationCompleted);
            }
            this.InvokeAsync("listaEncuestasPorFechaCierre", new object[] {
                        fechaInicial,
                        fechaFinal,
                        idAgente}, this.listaEncuestasPorFechaCierreOperationCompleted, userState);
        }
        
        private void OnlistaEncuestasPorFechaCierreOperationCompleted(object arg) {
            if ((this.listaEncuestasPorFechaCierreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaEncuestasPorFechaCierreCompleted(this, new listaEncuestasPorFechaCierreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaRoles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public rol[] listaRoles() {
            object[] results = this.Invoke("listaRoles", new object[0]);
            return ((rol[])(results[0]));
        }
        
        /// <remarks/>
        public void listaRolesAsync() {
            this.listaRolesAsync(null);
        }
        
        /// <remarks/>
        public void listaRolesAsync(object userState) {
            if ((this.listaRolesOperationCompleted == null)) {
                this.listaRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaRolesOperationCompleted);
            }
            this.InvokeAsync("listaRoles", new object[0], this.listaRolesOperationCompleted, userState);
        }
        
        private void OnlistaRolesOperationCompleted(object arg) {
            if ((this.listaRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaRolesCompleted(this, new listaRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/rolPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public rol rolPorId(int id) {
            object[] results = this.Invoke("rolPorId", new object[] {
                        id});
            return ((rol)(results[0]));
        }
        
        /// <remarks/>
        public void rolPorIdAsync(int id) {
            this.rolPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void rolPorIdAsync(int id, object userState) {
            if ((this.rolPorIdOperationCompleted == null)) {
                this.rolPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrolPorIdOperationCompleted);
            }
            this.InvokeAsync("rolPorId", new object[] {
                        id}, this.rolPorIdOperationCompleted, userState);
        }
        
        private void OnrolPorIdOperationCompleted(object arg) {
            if ((this.rolPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rolPorIdCompleted(this, new rolPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarRol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertarRol(rol unRol) {
            object[] results = this.Invoke("insertarRol", new object[] {
                        unRol});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertarRolAsync(rol unRol) {
            this.insertarRolAsync(unRol, null);
        }
        
        /// <remarks/>
        public void insertarRolAsync(rol unRol, object userState) {
            if ((this.insertarRolOperationCompleted == null)) {
                this.insertarRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarRolOperationCompleted);
            }
            this.InvokeAsync("insertarRol", new object[] {
                        unRol}, this.insertarRolOperationCompleted, userState);
        }
        
        private void OninsertarRolOperationCompleted(object arg) {
            if ((this.insertarRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarRolCompleted(this, new insertarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarRol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarRol(int id, rol unRol) {
            object[] results = this.Invoke("actualizarRol", new object[] {
                        id,
                        unRol});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarRolAsync(int id, rol unRol) {
            this.actualizarRolAsync(id, unRol, null);
        }
        
        /// <remarks/>
        public void actualizarRolAsync(int id, rol unRol, object userState) {
            if ((this.actualizarRolOperationCompleted == null)) {
                this.actualizarRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarRolOperationCompleted);
            }
            this.InvokeAsync("actualizarRol", new object[] {
                        id,
                        unRol}, this.actualizarRolOperationCompleted, userState);
        }
        
        private void OnactualizarRolOperationCompleted(object arg) {
            if ((this.actualizarRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarRolCompleted(this, new actualizarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class usuario {
        
        private string nombreField;
        
        private string emailField;
        
        private string id_usuarioField;
        
        private string contrasenaField;
        
        private string celularField;
        
        private string telefonoField;
        
        private System.Nullable<System.DateTime> f_ingresoField;
        
        private System.Nullable<int> id_rolField;
        
        private rol rolField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <remarks/>
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_ingreso {
            get {
                return this.f_ingresoField;
            }
            set {
                this.f_ingresoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> id_rol {
            get {
                return this.id_rolField;
            }
            set {
                this.id_rolField = value;
            }
        }
        
        /// <remarks/>
        public rol rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class rol {
        
        private int idField;
        
        private string nombreField;
        
        private string permisoField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string permiso {
            get {
                return this.permisoField;
            }
            set {
                this.permisoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class pregunta {
        
        private int idField;
        
        private string planteoField;
        
        private string condicionField;
        
        private System.Nullable<System.DateTime> f_ultima_respuestaField;
        
        private string id_encuestaField;
        
        private System.Nullable<int> nro_preguntaField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string planteo {
            get {
                return this.planteoField;
            }
            set {
                this.planteoField = value;
            }
        }
        
        /// <remarks/>
        public string condicion {
            get {
                return this.condicionField;
            }
            set {
                this.condicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_ultima_respuesta {
            get {
                return this.f_ultima_respuestaField;
            }
            set {
                this.f_ultima_respuestaField = value;
            }
        }
        
        /// <remarks/>
        public string id_encuesta {
            get {
                return this.id_encuestaField;
            }
            set {
                this.id_encuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> nro_pregunta {
            get {
                return this.nro_preguntaField;
            }
            set {
                this.nro_preguntaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class respuesta {
        
        private int idField;
        
        private int contadorField;
        
        private string textoField;
        
        private int id_preguntaField;
        
        private System.Nullable<int> id_proxima_preguntaField;
        
        private pregunta preguntaField;
        
        private pregunta pregunta1Field;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int contador {
            get {
                return this.contadorField;
            }
            set {
                this.contadorField = value;
            }
        }
        
        /// <remarks/>
        public string texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        public int id_pregunta {
            get {
                return this.id_preguntaField;
            }
            set {
                this.id_preguntaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> id_proxima_pregunta {
            get {
                return this.id_proxima_preguntaField;
            }
            set {
                this.id_proxima_preguntaField = value;
            }
        }
        
        /// <remarks/>
        public pregunta pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
            }
        }
        
        /// <remarks/>
        public pregunta pregunta1 {
            get {
                return this.pregunta1Field;
            }
            set {
                this.pregunta1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class encuesta {
        
        private string nombreField;
        
        private string contrasenaField;
        
        private System.DateTime f_ingresoField;
        
        private System.Nullable<System.DateTime> f_modificacionField;
        
        private System.Nullable<System.DateTime> f_vigenciaField;
        
        private System.Nullable<System.DateTime> f_cierreField;
        
        private string id_clienteField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_ingreso {
            get {
                return this.f_ingresoField;
            }
            set {
                this.f_ingresoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_modificacion {
            get {
                return this.f_modificacionField;
            }
            set {
                this.f_modificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_vigencia {
            get {
                return this.f_vigenciaField;
            }
            set {
                this.f_vigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_cierre {
            get {
                return this.f_cierreField;
            }
            set {
                this.f_cierreField = value;
            }
        }
        
        /// <remarks/>
        public string id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListaEncuestaResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultWs {
        
        private string errorField;
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaEncuestaResult : ResultWs {
        
        private encuesta[] listaEncuestasField;
        
        /// <remarks/>
        public encuesta[] ListaEncuestas {
            get {
                return this.listaEncuestasField;
            }
            set {
                this.listaEncuestasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void validarUsuarioCompletedEventHandler(object sender, validarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerPermisosPorUsuarioCompletedEventHandler(object sender, obtenerPermisosPorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPermisosPorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPermisosPorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaUsuariosCompletedEventHandler(object sender, listaUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaPorRolCompletedEventHandler(object sender, listaPorRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaPorRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaPorRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaClientePorAgenteCompletedEventHandler(object sender, listaClientePorAgenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaClientePorAgenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaClientePorAgenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void borrarUsuarioPorIdCompletedEventHandler(object sender, borrarUsuarioPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class borrarUsuarioPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal borrarUsuarioPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void usuarioPorIdCompletedEventHandler(object sender, usuarioPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class usuarioPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal usuarioPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void insertarUsuarioCompletedEventHandler(object sender, insertarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void actualizarUsuarioCompletedEventHandler(object sender, actualizarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaEncuestasCompletedEventHandler(object sender, listaEncuestasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaEncuestasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaEncuestasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaEncuestaResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaEncuestaResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void encuestaPorIdPasswordCompletedEventHandler(object sender, encuestaPorIdPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class encuestaPorIdPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal encuestaPorIdPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultWs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultWs)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void encuestaPorIdCompletedEventHandler(object sender, encuestaPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class encuestaPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal encuestaPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaEncuestaResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaEncuestaResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getPreguntaCompletedEventHandler(object sender, getPreguntaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPreguntaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPreguntaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultWs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultWs)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaEncuestasPorIdAgenteCompletedEventHandler(object sender, listaEncuestasPorIdAgenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaEncuestasPorIdAgenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaEncuestasPorIdAgenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public encuesta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((encuesta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaEncuestasPorIdClienteCompletedEventHandler(object sender, listaEncuestasPorIdClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaEncuestasPorIdClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaEncuestasPorIdClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public encuesta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((encuesta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void insertarEncuestaCompletedEventHandler(object sender, insertarEncuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarEncuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarEncuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void actualizarEncuestaCompletedEventHandler(object sender, actualizarEncuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarEncuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarEncuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaEncuestasPorFechaIngresoCompletedEventHandler(object sender, listaEncuestasPorFechaIngresoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaEncuestasPorFechaIngresoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaEncuestasPorFechaIngresoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public encuesta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((encuesta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaEncuestasPorFechaVigenciaCompletedEventHandler(object sender, listaEncuestasPorFechaVigenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaEncuestasPorFechaVigenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaEncuestasPorFechaVigenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public encuesta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((encuesta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaEncuestasPorFechaCierreCompletedEventHandler(object sender, listaEncuestasPorFechaCierreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaEncuestasPorFechaCierreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaEncuestasPorFechaCierreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public encuesta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((encuesta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listaRolesCompletedEventHandler(object sender, listaRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rol[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rol[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void rolPorIdCompletedEventHandler(object sender, rolPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rolPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rolPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rol Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rol)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void insertarRolCompletedEventHandler(object sender, insertarRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void actualizarRolCompletedEventHandler(object sender, actualizarRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591