<?xml version="1.0" encoding="utf-8"?>
<Database Name="etTempDB" EntityNamespace="encuestaTron.Models" ContextNamespace="encuestaTron" Class="dbModel" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=lorien\sqlexpress;Initial Catalog=eTronDb;Integrated Security=False;User ID=admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="etTempDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.usuario" Member="usuarios">
    <Type Name="usuario">
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Member="usuario1" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="f_ingreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="usuario_encuesta" Member="encuestas" ThisKey="usuario1" OtherKey="id_agente" Type="encuesta" />
      <Association Name="usuario_encuesta1" Member="encuestas1" ThisKey="usuario1" OtherKey="id_cliente" Type="encuesta" />
      <Association Name="usuario_permiso_usuario" Member="permiso_usuarios" ThisKey="usuario1" OtherKey="id_usuario" Type="permiso_usuario" />
    </Type>
  </Table>
  <Table Name="dbo.encuesta" Member="encuestas">
    <Type Name="encuesta">
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="f_ingreso" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="f_modificacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="f_vigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="f_cierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_agente" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="encuesta_pregunta" Member="preguntas" OtherKey="id_encuesta" Type="pregunta" />
      <Association Name="usuario_encuesta" Member="usuario" ThisKey="id_agente" OtherKey="usuario1" Type="usuario" IsForeignKey="true" />
      <Association Name="usuario_encuesta1" Member="usuario1" ThisKey="id_cliente" OtherKey="usuario1" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.permiso" Member="permisos">
    <Type Name="permiso">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="permiso" Member="permiso1" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="permiso_permiso_usuario" Member="permiso_usuarios" OtherKey="id_permiso" Type="permiso_usuario" />
    </Type>
  </Table>
  <Table Name="dbo.permiso_usuario" Member="permiso_usuarios">
    <Type Name="permiso_usuario">
      <Column Name="id_usuario" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_permiso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="permiso_permiso_usuario" Member="permiso" ThisKey="id_permiso" Type="permiso" IsForeignKey="true" />
      <Association Name="usuario_permiso_usuario" Member="usuario" ThisKey="id_usuario" OtherKey="usuario1" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pregunta" Member="preguntas">
    <Type Name="pregunta">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="planteo" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="condicion" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="f_ultima_respuesta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_encuesta" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="pregunta_respuesta" Member="respuestas" OtherKey="id_pregunta" Type="respuesta" />
      <Association Name="encuesta_pregunta" Member="encuesta" ThisKey="id_encuesta" Type="encuesta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.respuesta" Member="respuestas">
    <Type Name="respuesta">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="texto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_pregunta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="pregunta_respuesta" Member="pregunta" ThisKey="id_pregunta" Type="pregunta" IsForeignKey="true" />
    </Type>
  </Table>
</Database>