#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etBackend
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="encuestaTron")]
	public partial class db : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertencuesta(etBackend.Model.encuesta instance);
    partial void Updateencuesta(etBackend.Model.encuesta instance);
    partial void Deleteencuesta(etBackend.Model.encuesta instance);
    partial void Insertusuario(etBackend.Model.usuario instance);
    partial void Updateusuario(etBackend.Model.usuario instance);
    partial void Deleteusuario(etBackend.Model.usuario instance);
    partial void Insertpermiso(etBackend.Model.permiso instance);
    partial void Updatepermiso(etBackend.Model.permiso instance);
    partial void Deletepermiso(etBackend.Model.permiso instance);
    partial void Insertpermiso_usuario(etBackend.Model.permiso_usuario instance);
    partial void Updatepermiso_usuario(etBackend.Model.permiso_usuario instance);
    partial void Deletepermiso_usuario(etBackend.Model.permiso_usuario instance);
    partial void Insertpregunta(etBackend.Model.pregunta instance);
    partial void Updatepregunta(etBackend.Model.pregunta instance);
    partial void Deletepregunta(etBackend.Model.pregunta instance);
    partial void Insertrespuesta(etBackend.Model.respuesta instance);
    partial void Updaterespuesta(etBackend.Model.respuesta instance);
    partial void Deleterespuesta(etBackend.Model.respuesta instance);
    #endregion
		
		public db() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["encuestaTronConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public db(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<etBackend.Model.encuesta> encuestas
		{
			get
			{
				return this.GetTable<etBackend.Model.encuesta>();
			}
		}
		
		public System.Data.Linq.Table<etBackend.Model.usuario> usuarios
		{
			get
			{
				return this.GetTable<etBackend.Model.usuario>();
			}
		}
		
		public System.Data.Linq.Table<etBackend.Model.permiso> permisos
		{
			get
			{
				return this.GetTable<etBackend.Model.permiso>();
			}
		}
		
		public System.Data.Linq.Table<etBackend.Model.permiso_usuario> permiso_usuarios
		{
			get
			{
				return this.GetTable<etBackend.Model.permiso_usuario>();
			}
		}
		
		public System.Data.Linq.Table<etBackend.Model.pregunta> preguntas
		{
			get
			{
				return this.GetTable<etBackend.Model.pregunta>();
			}
		}
		
		public System.Data.Linq.Table<etBackend.Model.respuesta> respuestas
		{
			get
			{
				return this.GetTable<etBackend.Model.respuesta>();
			}
		}
	}
}
namespace etBackend.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[Table(Name="dbo.encuesta")]
	public partial class encuesta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre;
		
		private string _contrasena;
		
		private System.DateTime _f_ingreso;
		
		private System.Nullable<System.DateTime> _f_modificacion;
		
		private System.Nullable<System.DateTime> _f_vigencia;
		
		private System.Nullable<System.DateTime> _f_cierre;
		
		private string _id_agente;
		
		private string _id_cliente;
		
		private EntitySet<pregunta> _preguntas;
		
		private EntityRef<usuario> _usuario;
		
		private EntityRef<usuario> _usuario1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void Onf_ingresoChanging(System.DateTime value);
    partial void Onf_ingresoChanged();
    partial void Onf_modificacionChanging(System.Nullable<System.DateTime> value);
    partial void Onf_modificacionChanged();
    partial void Onf_vigenciaChanging(System.Nullable<System.DateTime> value);
    partial void Onf_vigenciaChanged();
    partial void Onf_cierreChanging(System.Nullable<System.DateTime> value);
    partial void Onf_cierreChanged();
    partial void Onid_agenteChanging(string value);
    partial void Onid_agenteChanged();
    partial void Onid_clienteChanging(string value);
    partial void Onid_clienteChanged();
    #endregion
		
		public encuesta()
		{
			this._preguntas = new EntitySet<pregunta>(new Action<pregunta>(this.attach_preguntas), new Action<pregunta>(this.detach_preguntas));
			this._usuario = default(EntityRef<usuario>);
			this._usuario1 = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[Column(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[Column(Storage="_contrasena", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[Column(Storage="_f_ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime f_ingreso
		{
			get
			{
				return this._f_ingreso;
			}
			set
			{
				if ((this._f_ingreso != value))
				{
					this.Onf_ingresoChanging(value);
					this.SendPropertyChanging();
					this._f_ingreso = value;
					this.SendPropertyChanged("f_ingreso");
					this.Onf_ingresoChanged();
				}
			}
		}
		
		[Column(Storage="_f_modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_modificacion
		{
			get
			{
				return this._f_modificacion;
			}
			set
			{
				if ((this._f_modificacion != value))
				{
					this.Onf_modificacionChanging(value);
					this.SendPropertyChanging();
					this._f_modificacion = value;
					this.SendPropertyChanged("f_modificacion");
					this.Onf_modificacionChanged();
				}
			}
		}
		
		[Column(Storage="_f_vigencia", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_vigencia
		{
			get
			{
				return this._f_vigencia;
			}
			set
			{
				if ((this._f_vigencia != value))
				{
					this.Onf_vigenciaChanging(value);
					this.SendPropertyChanging();
					this._f_vigencia = value;
					this.SendPropertyChanged("f_vigencia");
					this.Onf_vigenciaChanged();
				}
			}
		}
		
		[Column(Storage="_f_cierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_cierre
		{
			get
			{
				return this._f_cierre;
			}
			set
			{
				if ((this._f_cierre != value))
				{
					this.Onf_cierreChanging(value);
					this.SendPropertyChanging();
					this._f_cierre = value;
					this.SendPropertyChanged("f_cierre");
					this.Onf_cierreChanged();
				}
			}
		}
		
		[Column(Storage="_id_agente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_agente
		{
			get
			{
				return this._id_agente;
			}
			set
			{
				if ((this._id_agente != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_agenteChanging(value);
					this.SendPropertyChanging();
					this._id_agente = value;
					this.SendPropertyChanged("id_agente");
					this.Onid_agenteChanged();
				}
			}
		}
		
		[Column(Storage="_id_cliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[Association(Name="encuesta_pregunta", Storage="_preguntas", OtherKey="id_encuesta")]
		public EntitySet<pregunta> preguntas
		{
			get
			{
				return this._preguntas;
			}
			set
			{
				this._preguntas.Assign(value);
			}
		}
		
		[Association(Name="usuario_encuesta", Storage="_usuario", ThisKey="id_agente", OtherKey="usuario1", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.encuestas.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.encuestas.Add(this);
						this._id_agente = value.usuario1;
					}
					else
					{
						this._id_agente = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		[Association(Name="usuario_encuesta1", Storage="_usuario1", ThisKey="id_cliente", OtherKey="usuario1", IsForeignKey=true)]
		public usuario usuario1
		{
			get
			{
				return this._usuario1.Entity;
			}
			set
			{
				usuario previousValue = this._usuario1.Entity;
				if (((previousValue != value) 
							|| (this._usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario1.Entity = null;
						previousValue.encuestas1.Remove(this);
					}
					this._usuario1.Entity = value;
					if ((value != null))
					{
						value.encuestas1.Add(this);
						this._id_cliente = value.usuario1;
					}
					else
					{
						this._id_cliente = default(string);
					}
					this.SendPropertyChanged("usuario1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_preguntas(pregunta entity)
		{
			this.SendPropertyChanging();
			entity.encuesta = this;
		}
		
		private void detach_preguntas(pregunta entity)
		{
			this.SendPropertyChanging();
			entity.encuesta = null;
		}
	}
	
	[Table(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre;
		
		private string _email;
		
		private string _usuario1;
		
		private string _contrasena;
		
		private string _celular;
		
		private string _telefono;
		
		private System.Nullable<System.DateTime> _f_ingreso;
		
		private EntitySet<encuesta> _encuestas;
		
		private EntitySet<encuesta> _encuestas1;
		
		private EntitySet<permiso_usuario> _permiso_usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Onf_ingresoChanging(System.Nullable<System.DateTime> value);
    partial void Onf_ingresoChanged();
    #endregion
		
		public usuario()
		{
			this._encuestas = new EntitySet<encuesta>(new Action<encuesta>(this.attach_encuestas), new Action<encuesta>(this.detach_encuestas));
			this._encuestas1 = new EntitySet<encuesta>(new Action<encuesta>(this.attach_encuestas1), new Action<encuesta>(this.detach_encuestas1));
			this._permiso_usuarios = new EntitySet<permiso_usuario>(new Action<permiso_usuario>(this.attach_permiso_usuarios), new Action<permiso_usuario>(this.detach_permiso_usuarios));
			OnCreated();
		}
		
		[Column(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Name="usuario", Storage="_usuario1", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string usuario1
		{
			get
			{
				return this._usuario1;
			}
			set
			{
				if ((this._usuario1 != value))
				{
					this.Onusuario1Changing(value);
					this.SendPropertyChanging();
					this._usuario1 = value;
					this.SendPropertyChanged("usuario1");
					this.Onusuario1Changed();
				}
			}
		}
		
		[Column(Storage="_contrasena", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[Column(Storage="_celular", DbType="VarChar(50)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[Column(Storage="_telefono", DbType="VarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[Column(Storage="_f_ingreso", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_ingreso
		{
			get
			{
				return this._f_ingreso;
			}
			set
			{
				if ((this._f_ingreso != value))
				{
					this.Onf_ingresoChanging(value);
					this.SendPropertyChanging();
					this._f_ingreso = value;
					this.SendPropertyChanged("f_ingreso");
					this.Onf_ingresoChanged();
				}
			}
		}
		
		[Association(Name="usuario_encuesta", Storage="_encuestas", ThisKey="usuario1", OtherKey="id_agente")]
		public EntitySet<encuesta> encuestas
		{
			get
			{
				return this._encuestas;
			}
			set
			{
				this._encuestas.Assign(value);
			}
		}
		
		[Association(Name="usuario_encuesta1", Storage="_encuestas1", ThisKey="usuario1", OtherKey="id_cliente")]
		public EntitySet<encuesta> encuestas1
		{
			get
			{
				return this._encuestas1;
			}
			set
			{
				this._encuestas1.Assign(value);
			}
		}
		
		[Association(Name="usuario_permiso_usuario", Storage="_permiso_usuarios", ThisKey="usuario1", OtherKey="id_usuario")]
		public EntitySet<permiso_usuario> permiso_usuarios
		{
			get
			{
				return this._permiso_usuarios;
			}
			set
			{
				this._permiso_usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_encuestas(encuesta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_encuestas(encuesta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_encuestas1(encuesta entity)
		{
			this.SendPropertyChanging();
			entity.usuario1 = this;
		}
		
		private void detach_encuestas1(encuesta entity)
		{
			this.SendPropertyChanging();
			entity.usuario1 = null;
		}
		
		private void attach_permiso_usuarios(permiso_usuario entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_permiso_usuarios(permiso_usuario entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
	
	[Table(Name="dbo.permiso")]
	public partial class permiso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<permiso_usuario> _permiso_usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public permiso()
		{
			this._permiso_usuarios = new EntitySet<permiso_usuario>(new Action<permiso_usuario>(this.attach_permiso_usuarios), new Action<permiso_usuario>(this.detach_permiso_usuarios));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_nombre", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[Column(Storage="_descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[Association(Name="permiso_permiso_usuario", Storage="_permiso_usuarios", OtherKey="id_permiso")]
		public EntitySet<permiso_usuario> permiso_usuarios
		{
			get
			{
				return this._permiso_usuarios;
			}
			set
			{
				this._permiso_usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_permiso_usuarios(permiso_usuario entity)
		{
			this.SendPropertyChanging();
			entity.permiso = this;
		}
		
		private void detach_permiso_usuarios(permiso_usuario entity)
		{
			this.SendPropertyChanging();
			entity.permiso = null;
		}
	}
	
	[Table(Name="dbo.permiso_usuario")]
	public partial class permiso_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_usuario;
		
		private int _id_permiso;
		
		private EntityRef<permiso> _permiso;
		
		private EntityRef<usuario> _usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(string value);
    partial void Onid_usuarioChanged();
    partial void Onid_permisoChanging(int value);
    partial void Onid_permisoChanged();
    #endregion
		
		public permiso_usuario()
		{
			this._permiso = default(EntityRef<permiso>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[Column(Storage="_id_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[Column(Storage="_id_permiso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_permiso
		{
			get
			{
				return this._id_permiso;
			}
			set
			{
				if ((this._id_permiso != value))
				{
					if (this._permiso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_permisoChanging(value);
					this.SendPropertyChanging();
					this._id_permiso = value;
					this.SendPropertyChanged("id_permiso");
					this.Onid_permisoChanged();
				}
			}
		}
		
		[Association(Name="permiso_permiso_usuario", Storage="_permiso", ThisKey="id_permiso", IsForeignKey=true)]
		public permiso permiso
		{
			get
			{
				return this._permiso.Entity;
			}
			set
			{
				permiso previousValue = this._permiso.Entity;
				if (((previousValue != value) 
							|| (this._permiso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._permiso.Entity = null;
						previousValue.permiso_usuarios.Remove(this);
					}
					this._permiso.Entity = value;
					if ((value != null))
					{
						value.permiso_usuarios.Add(this);
						this._id_permiso = value.id;
					}
					else
					{
						this._id_permiso = default(int);
					}
					this.SendPropertyChanged("permiso");
				}
			}
		}
		
		[Association(Name="usuario_permiso_usuario", Storage="_usuario", ThisKey="id_usuario", OtherKey="usuario1", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.permiso_usuarios.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.permiso_usuarios.Add(this);
						this._id_usuario = value.usuario1;
					}
					else
					{
						this._id_usuario = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.pregunta")]
	public partial class pregunta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _planteo;
		
		private string _condicion;
		
		private System.Nullable<System.DateTime> _f_ultima_respuesta;
		
		private string _id_encuesta;
		
		private EntitySet<respuesta> _respuestas;
		
		private EntityRef<encuesta> _encuesta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnplanteoChanging(string value);
    partial void OnplanteoChanged();
    partial void OncondicionChanging(string value);
    partial void OncondicionChanged();
    partial void Onf_ultima_respuestaChanging(System.Nullable<System.DateTime> value);
    partial void Onf_ultima_respuestaChanged();
    partial void Onid_encuestaChanging(string value);
    partial void Onid_encuestaChanged();
    #endregion
		
		public pregunta()
		{
			this._respuestas = new EntitySet<respuesta>(new Action<respuesta>(this.attach_respuestas), new Action<respuesta>(this.detach_respuestas));
			this._encuesta = default(EntityRef<encuesta>);
			OnCreated();
		}
		
		[Column(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_planteo", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string planteo
		{
			get
			{
				return this._planteo;
			}
			set
			{
				if ((this._planteo != value))
				{
					this.OnplanteoChanging(value);
					this.SendPropertyChanging();
					this._planteo = value;
					this.SendPropertyChanged("planteo");
					this.OnplanteoChanged();
				}
			}
		}
		
		[Column(Storage="_condicion", DbType="NChar(10)")]
		public string condicion
		{
			get
			{
				return this._condicion;
			}
			set
			{
				if ((this._condicion != value))
				{
					this.OncondicionChanging(value);
					this.SendPropertyChanging();
					this._condicion = value;
					this.SendPropertyChanged("condicion");
					this.OncondicionChanged();
				}
			}
		}
		
		[Column(Storage="_f_ultima_respuesta", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_ultima_respuesta
		{
			get
			{
				return this._f_ultima_respuesta;
			}
			set
			{
				if ((this._f_ultima_respuesta != value))
				{
					this.Onf_ultima_respuestaChanging(value);
					this.SendPropertyChanging();
					this._f_ultima_respuesta = value;
					this.SendPropertyChanged("f_ultima_respuesta");
					this.Onf_ultima_respuestaChanged();
				}
			}
		}
		
		[Column(Storage="_id_encuesta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_encuesta
		{
			get
			{
				return this._id_encuesta;
			}
			set
			{
				if ((this._id_encuesta != value))
				{
					if (this._encuesta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_encuestaChanging(value);
					this.SendPropertyChanging();
					this._id_encuesta = value;
					this.SendPropertyChanged("id_encuesta");
					this.Onid_encuestaChanged();
				}
			}
		}
		
		[Association(Name="pregunta_respuesta", Storage="_respuestas", OtherKey="id_pregunta")]
		public EntitySet<respuesta> respuestas
		{
			get
			{
				return this._respuestas;
			}
			set
			{
				this._respuestas.Assign(value);
			}
		}
		
		[Association(Name="encuesta_pregunta", Storage="_encuesta", ThisKey="id_encuesta", IsForeignKey=true)]
		public encuesta encuesta
		{
			get
			{
				return this._encuesta.Entity;
			}
			set
			{
				encuesta previousValue = this._encuesta.Entity;
				if (((previousValue != value) 
							|| (this._encuesta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._encuesta.Entity = null;
						previousValue.preguntas.Remove(this);
					}
					this._encuesta.Entity = value;
					if ((value != null))
					{
						value.preguntas.Add(this);
						this._id_encuesta = value.nombre;
					}
					else
					{
						this._id_encuesta = default(string);
					}
					this.SendPropertyChanged("encuesta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_respuestas(respuesta entity)
		{
			this.SendPropertyChanging();
			entity.pregunta = this;
		}
		
		private void detach_respuestas(respuesta entity)
		{
			this.SendPropertyChanging();
			entity.pregunta = null;
		}
	}
	
	[Table(Name="dbo.respuesta")]
	public partial class respuesta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _contador;
		
		private string _texto;
		
		private int _id_pregunta;
		
		private EntityRef<pregunta> _pregunta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncontadorChanging(int value);
    partial void OncontadorChanged();
    partial void OntextoChanging(string value);
    partial void OntextoChanged();
    partial void Onid_preguntaChanging(int value);
    partial void Onid_preguntaChanged();
    #endregion
		
		public respuesta()
		{
			this._pregunta = default(EntityRef<pregunta>);
			OnCreated();
		}
		
		[Column(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_contador", DbType="Int NOT NULL")]
		public int contador
		{
			get
			{
				return this._contador;
			}
			set
			{
				if ((this._contador != value))
				{
					this.OncontadorChanging(value);
					this.SendPropertyChanging();
					this._contador = value;
					this.SendPropertyChanged("contador");
					this.OncontadorChanged();
				}
			}
		}
		
		[Column(Storage="_texto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string texto
		{
			get
			{
				return this._texto;
			}
			set
			{
				if ((this._texto != value))
				{
					this.OntextoChanging(value);
					this.SendPropertyChanging();
					this._texto = value;
					this.SendPropertyChanged("texto");
					this.OntextoChanged();
				}
			}
		}
		
		[Column(Storage="_id_pregunta", DbType="Int NOT NULL")]
		public int id_pregunta
		{
			get
			{
				return this._id_pregunta;
			}
			set
			{
				if ((this._id_pregunta != value))
				{
					if (this._pregunta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_preguntaChanging(value);
					this.SendPropertyChanging();
					this._id_pregunta = value;
					this.SendPropertyChanged("id_pregunta");
					this.Onid_preguntaChanged();
				}
			}
		}
		
		[Association(Name="pregunta_respuesta", Storage="_pregunta", ThisKey="id_pregunta", IsForeignKey=true)]
		public pregunta pregunta
		{
			get
			{
				return this._pregunta.Entity;
			}
			set
			{
				pregunta previousValue = this._pregunta.Entity;
				if (((previousValue != value) 
							|| (this._pregunta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pregunta.Entity = null;
						previousValue.respuestas.Remove(this);
					}
					this._pregunta.Entity = value;
					if ((value != null))
					{
						value.respuestas.Add(this);
						this._id_pregunta = value.id;
					}
					else
					{
						this._id_pregunta = default(int);
					}
					this.SendPropertyChanged("pregunta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
