#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etBackend
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="encuestaTron")]
	public partial class DB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEncuesta(etBackend.Model.Encuesta instance);
    partial void UpdateEncuesta(etBackend.Model.Encuesta instance);
    partial void DeleteEncuesta(etBackend.Model.Encuesta instance);
    #endregion
		
		public DB() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["encuestaTronConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<etBackend.Model.Encuesta> Encuestas
		{
			get
			{
				return this.GetTable<etBackend.Model.Encuesta>();
			}
		}
	}
}
namespace etBackend.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[Table(Name="dbo.encuesta")]
	public partial class Encuesta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre;
		
		private string _contrasena;
		
		private System.DateTime _f_ingreso;
		
		private System.Nullable<System.DateTime> _f_modificacion;
		
		private System.Nullable<System.DateTime> _f_vigencia;
		
		private System.Nullable<System.DateTime> _f_cierre;
		
		private string _id_agente;
		
		private string _id_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void Onf_ingresoChanging(System.DateTime value);
    partial void Onf_ingresoChanged();
    partial void Onf_modificacionChanging(System.Nullable<System.DateTime> value);
    partial void Onf_modificacionChanged();
    partial void Onf_vigenciaChanging(System.Nullable<System.DateTime> value);
    partial void Onf_vigenciaChanged();
    partial void Onf_cierreChanging(System.Nullable<System.DateTime> value);
    partial void Onf_cierreChanged();
    partial void Onid_agenteChanging(string value);
    partial void Onid_agenteChanged();
    partial void Onid_clienteChanging(string value);
    partial void Onid_clienteChanged();
    #endregion
		
		public Encuesta()
		{
			OnCreated();
		}
		
		[Column(Storage="_nombre", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[Column(Storage="_contrasena", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[Column(Storage="_f_ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime f_ingreso
		{
			get
			{
				return this._f_ingreso;
			}
			set
			{
				if ((this._f_ingreso != value))
				{
					this.Onf_ingresoChanging(value);
					this.SendPropertyChanging();
					this._f_ingreso = value;
					this.SendPropertyChanged("f_ingreso");
					this.Onf_ingresoChanged();
				}
			}
		}
		
		[Column(Storage="_f_modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_modificacion
		{
			get
			{
				return this._f_modificacion;
			}
			set
			{
				if ((this._f_modificacion != value))
				{
					this.Onf_modificacionChanging(value);
					this.SendPropertyChanging();
					this._f_modificacion = value;
					this.SendPropertyChanged("f_modificacion");
					this.Onf_modificacionChanged();
				}
			}
		}
		
		[Column(Storage="_f_vigencia", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_vigencia
		{
			get
			{
				return this._f_vigencia;
			}
			set
			{
				if ((this._f_vigencia != value))
				{
					this.Onf_vigenciaChanging(value);
					this.SendPropertyChanging();
					this._f_vigencia = value;
					this.SendPropertyChanged("f_vigencia");
					this.Onf_vigenciaChanged();
				}
			}
		}
		
		[Column(Storage="_f_cierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> f_cierre
		{
			get
			{
				return this._f_cierre;
			}
			set
			{
				if ((this._f_cierre != value))
				{
					this.Onf_cierreChanging(value);
					this.SendPropertyChanging();
					this._f_cierre = value;
					this.SendPropertyChanged("f_cierre");
					this.Onf_cierreChanged();
				}
			}
		}
		
		[Column(Storage="_id_agente", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id_agente
		{
			get
			{
				return this._id_agente;
			}
			set
			{
				if ((this._id_agente != value))
				{
					this.Onid_agenteChanging(value);
					this.SendPropertyChanging();
					this._id_agente = value;
					this.SendPropertyChanged("id_agente");
					this.Onid_agenteChanged();
				}
			}
		}
		
		[Column(Storage="_id_cliente", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
