//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace miSitio.Com.etWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="etWebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultWs2))]
    public partial class etWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getListaEncuestasOperationCompleted;
        
        private System.Threading.SendOrPostCallback encuestaPorIdPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSiguientePreguntaEncuestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarEncuestaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public etWebService() {
            this.Url = global::miSitio.Com.Properties.Settings.Default.miSitio_Com_etWebService_etWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getListaEncuestasCompletedEventHandler getListaEncuestasCompleted;
        
        /// <remarks/>
        public event encuestaPorIdPasswordCompletedEventHandler encuestaPorIdPasswordCompleted;
        
        /// <remarks/>
        public event getSiguientePreguntaEncuestaCompletedEventHandler getSiguientePreguntaEncuestaCompleted;
        
        /// <remarks/>
        public event guardarEncuestaCompletedEventHandler guardarEncuestaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getListaEncuestas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaEncuestaResult2 getListaEncuestas() {
            object[] results = this.Invoke("getListaEncuestas", new object[0]);
            return ((ListaEncuestaResult2)(results[0]));
        }
        
        /// <remarks/>
        public void getListaEncuestasAsync() {
            this.getListaEncuestasAsync(null);
        }
        
        /// <remarks/>
        public void getListaEncuestasAsync(object userState) {
            if ((this.getListaEncuestasOperationCompleted == null)) {
                this.getListaEncuestasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListaEncuestasOperationCompleted);
            }
            this.InvokeAsync("getListaEncuestas", new object[0], this.getListaEncuestasOperationCompleted, userState);
        }
        
        private void OngetListaEncuestasOperationCompleted(object arg) {
            if ((this.getListaEncuestasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListaEncuestasCompleted(this, new getListaEncuestasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/encuestaPorIdPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaEncuestaResult2 encuestaPorIdPassword(string id, string pass) {
            object[] results = this.Invoke("encuestaPorIdPassword", new object[] {
                        id,
                        pass});
            return ((ListaEncuestaResult2)(results[0]));
        }
        
        /// <remarks/>
        public void encuestaPorIdPasswordAsync(string id, string pass) {
            this.encuestaPorIdPasswordAsync(id, pass, null);
        }
        
        /// <remarks/>
        public void encuestaPorIdPasswordAsync(string id, string pass, object userState) {
            if ((this.encuestaPorIdPasswordOperationCompleted == null)) {
                this.encuestaPorIdPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnencuestaPorIdPasswordOperationCompleted);
            }
            this.InvokeAsync("encuestaPorIdPassword", new object[] {
                        id,
                        pass}, this.encuestaPorIdPasswordOperationCompleted, userState);
        }
        
        private void OnencuestaPorIdPasswordOperationCompleted(object arg) {
            if ((this.encuestaPorIdPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encuestaPorIdPasswordCompleted(this, new encuestaPorIdPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSiguientePreguntaEncuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public getPreguntaResult2 getSiguientePreguntaEncuesta(respuesta respuesta) {
            object[] results = this.Invoke("getSiguientePreguntaEncuesta", new object[] {
                        respuesta});
            return ((getPreguntaResult2)(results[0]));
        }
        
        /// <remarks/>
        public void getSiguientePreguntaEncuestaAsync(respuesta respuesta) {
            this.getSiguientePreguntaEncuestaAsync(respuesta, null);
        }
        
        /// <remarks/>
        public void getSiguientePreguntaEncuestaAsync(respuesta respuesta, object userState) {
            if ((this.getSiguientePreguntaEncuestaOperationCompleted == null)) {
                this.getSiguientePreguntaEncuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSiguientePreguntaEncuestaOperationCompleted);
            }
            this.InvokeAsync("getSiguientePreguntaEncuesta", new object[] {
                        respuesta}, this.getSiguientePreguntaEncuestaOperationCompleted, userState);
        }
        
        private void OngetSiguientePreguntaEncuestaOperationCompleted(object arg) {
            if ((this.getSiguientePreguntaEncuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSiguientePreguntaEncuestaCompleted(this, new getSiguientePreguntaEncuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarEncuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultWs guardarEncuesta(respuesta[] respuestas) {
            object[] results = this.Invoke("guardarEncuesta", new object[] {
                        respuestas});
            return ((ResultWs)(results[0]));
        }
        
        /// <remarks/>
        public void guardarEncuestaAsync(respuesta[] respuestas) {
            this.guardarEncuestaAsync(respuestas, null);
        }
        
        /// <remarks/>
        public void guardarEncuestaAsync(respuesta[] respuestas, object userState) {
            if ((this.guardarEncuestaOperationCompleted == null)) {
                this.guardarEncuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarEncuestaOperationCompleted);
            }
            this.InvokeAsync("guardarEncuesta", new object[] {
                        respuestas}, this.guardarEncuestaOperationCompleted, userState);
        }
        
        private void OnguardarEncuestaOperationCompleted(object arg) {
            if ((this.guardarEncuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarEncuestaCompleted(this, new guardarEncuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaEncuestaResult2 : ResultWs2 {
        
        private EncuestaPortal[] listaEncuestasField;
        
        /// <remarks/>
        public EncuestaPortal[] ListaEncuestas {
            get {
                return this.listaEncuestasField;
            }
            set {
                this.listaEncuestasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EncuestaPortal {
        
        private pregunta[] preguntasField;
        
        private string nombreField;
        
        private string accionField;
        
        private System.DateTime fechaDesdeField;
        
        private System.DateTime fechaFinField;
        
        /// <remarks/>
        public pregunta[] Preguntas {
            get {
                return this.preguntasField;
            }
            set {
                this.preguntasField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaDesde {
            get {
                return this.fechaDesdeField;
            }
            set {
                this.fechaDesdeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class pregunta {
        
        private int idField;
        
        private string planteoField;
        
        private string condicionField;
        
        private System.Nullable<System.DateTime> f_ultima_respuestaField;
        
        private string id_encuestaField;
        
        private System.Nullable<int> nro_preguntaField;
        
        private respuesta[] respuestasField;
        
        private respuesta respuestaField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string planteo {
            get {
                return this.planteoField;
            }
            set {
                this.planteoField = value;
            }
        }
        
        /// <remarks/>
        public string condicion {
            get {
                return this.condicionField;
            }
            set {
                this.condicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_ultima_respuesta {
            get {
                return this.f_ultima_respuestaField;
            }
            set {
                this.f_ultima_respuestaField = value;
            }
        }
        
        /// <remarks/>
        public string id_encuesta {
            get {
                return this.id_encuestaField;
            }
            set {
                this.id_encuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> nro_pregunta {
            get {
                return this.nro_preguntaField;
            }
            set {
                this.nro_preguntaField = value;
            }
        }
        
        /// <remarks/>
        public respuesta[] respuestas {
            get {
                return this.respuestasField;
            }
            set {
                this.respuestasField = value;
            }
        }
        
        /// <remarks/>
        public respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class respuesta {
        
        private int idField;
        
        private int contadorField;
        
        private string textoField;
        
        private int id_preguntaField;
        
        private System.Nullable<int> id_proxima_preguntaField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int contador {
            get {
                return this.contadorField;
            }
            set {
                this.contadorField = value;
            }
        }
        
        /// <remarks/>
        public string texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        public int id_pregunta {
            get {
                return this.id_preguntaField;
            }
            set {
                this.id_preguntaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> id_proxima_pregunta {
            get {
                return this.id_proxima_preguntaField;
            }
            set {
                this.id_proxima_preguntaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class encuesta {
        
        private string nombreField;
        
        private string contrasenaField;
        
        private System.DateTime f_ingresoField;
        
        private System.Nullable<System.DateTime> f_modificacionField;
        
        private System.Nullable<System.DateTime> f_vigenciaField;
        
        private System.Nullable<System.DateTime> f_cierreField;
        
        private string id_clienteField;
        
        private pregunta[] preguntasField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_ingreso {
            get {
                return this.f_ingresoField;
            }
            set {
                this.f_ingresoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_modificacion {
            get {
                return this.f_modificacionField;
            }
            set {
                this.f_modificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_vigencia {
            get {
                return this.f_vigenciaField;
            }
            set {
                this.f_vigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> f_cierre {
            get {
                return this.f_cierreField;
            }
            set {
                this.f_cierreField = value;
            }
        }
        
        /// <remarks/>
        public string id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
            }
        }
        
        /// <remarks/>
        public pregunta[] preguntas {
            get {
                return this.preguntasField;
            }
            set {
                this.preguntasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getPreguntaResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListaEncuestaResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultWs {
        
        private string errorField;
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntaResult : ResultWs {
        
        private pregunta preguntaField;
        
        /// <remarks/>
        public pregunta Pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaEncuestaResult : ResultWs {
        
        private encuesta[] listaEncuestasField;
        
        /// <remarks/>
        public encuesta[] ListaEncuestas {
            get {
                return this.listaEncuestasField;
            }
            set {
                this.listaEncuestasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getPreguntaResult2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListaEncuestaResult2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultWs2 {
        
        private string errorField;
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntaResult2 : ResultWs2 {
        
        private pregunta preguntaField;
        
        /// <remarks/>
        public pregunta Pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getListaEncuestasCompletedEventHandler(object sender, getListaEncuestasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListaEncuestasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListaEncuestasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaEncuestaResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaEncuestaResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void encuestaPorIdPasswordCompletedEventHandler(object sender, encuestaPorIdPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class encuestaPorIdPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal encuestaPorIdPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaEncuestaResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaEncuestaResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getSiguientePreguntaEncuestaCompletedEventHandler(object sender, getSiguientePreguntaEncuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSiguientePreguntaEncuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSiguientePreguntaEncuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getPreguntaResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getPreguntaResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void guardarEncuestaCompletedEventHandler(object sender, guardarEncuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarEncuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarEncuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultWs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultWs)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591