<?xml version="1.0" encoding="utf-8"?>
<Database Name="eTronDB" EntityNamespace="encuestaTron" ContextNamespace="encuestaTron.Models" Class="dbModel" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LORIEN\SQLEXPRESS;Initial Catalog=eTronDB;Persist Security Info=True;User ID=admin" SettingsObjectName="DataTypesObjects.Properties.Settings" SettingsPropertyName="eTronDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bitacora" Member="bitacoras">
    <Type Name="bitacora">
      <Column Name="id_Log" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_Log" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="usuario_Log" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_Log" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="severidad_Log" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.usuario" Member="usuarios">
    <Type Name="usuario">
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="f_ingreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="usuario_cliente" Member="clientes" AccessModifier="Internal" OtherKey="id_agente" Type="cliente" />
      <Association Name="rol_usuario" Member="rol" ThisKey="id_rol" Type="rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cliente" Member="clientes">
    <Type Name="cliente">
      <Column Name="id_usuario" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_agente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="cliente_cliente" Member="cliente2" AccessModifier="Internal" OtherKey="id_usuario" Type="cliente" Cardinality="One" />
      <Association Name="cliente_encuesta" Member="encuestas" AccessModifier="Internal" OtherKey="id_cliente" Type="encuesta" />
      <Association Name="usuario_cliente" Member="usuario" ThisKey="id_agente" Type="usuario" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="cliente_cliente" Member="cliente1" ThisKey="id_usuario" Type="cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.encuesta" Member="encuestas">
    <Type Name="encuesta">
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="f_ingreso" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="f_modificacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="f_vigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="f_cierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_cliente" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="encuesta_pregunta" Member="preguntas" OtherKey="id_encuesta" Type="pregunta" />
      <Association Name="cliente_encuesta" Member="cliente" AccessModifier="Internal" ThisKey="id_cliente" Type="cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.rol" Member="rols">
    <Type Name="rol">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="permiso" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="rol_usuario" Member="usuarios" AccessModifier="Internal" OtherKey="id_rol" Type="usuario" />
    </Type>
  </Table>
  <Table Name="dbo.pregunta" Member="preguntas">
    <Type Name="pregunta">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="planteo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="condicion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="f_ultima_respuesta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_encuesta" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nro_pregunta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="pregunta_respuesta" Member="respuestas" OtherKey="id_pregunta" Type="respuesta" />
      <Association Name="pregunta_respuesta1" Member="respuesta" OtherKey="id" Type="respuesta" Cardinality="One" />
      <Association Name="encuesta_pregunta" Member="encuesta" AccessModifier="Internal" ThisKey="id_encuesta" Type="encuesta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.respuesta" Member="respuestas">
    <Type Name="respuesta">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="texto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_pregunta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_proxima_pregunta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="pregunta_respuesta" Member="pregunta" AccessModifier="Internal" ThisKey="id_pregunta" Type="pregunta" IsForeignKey="true" />
      <Association Name="pregunta_respuesta1" Member="pregunta1" AccessModifier="Internal" ThisKey="id" Type="pregunta" IsForeignKey="true" />
    </Type>
  </Table>
</Database>